# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

A11_update <- function(A11_old, p, q, x, z, sigma2_A, w, gamma, beta, Lambda, delta, w1, metrop_var_A11_trans, acctot_A11_trans) {
    .Call(`_CWVSmix_A11_update`, A11_old, p, q, x, z, sigma2_A, w, gamma, beta, Lambda, delta, w1, metrop_var_A11_trans, acctot_A11_trans)
}

A21_update <- function(sigma2_A, delta_star, w1, w2, A22) {
    .Call(`_CWVSmix_A21_update`, sigma2_A, delta_star, w1, w2, A22)
}

A22_update <- function(A22_old, sigma2_A, delta_star, w1, w2, A21_old, metrop_var_A22_trans, acctot_A22_trans) {
    .Call(`_CWVSmix_A22_update`, A22_old, sigma2_A, delta_star, w1, w2, A21_old, metrop_var_A22_trans, acctot_A22_trans)
}

CWVSmix <- function(mcmc_samples, p, q, y, x, z, mh_scale_Lambda, metrop_var_A11_trans, metrop_var_A22_trans, metrop_var_phi1_trans, metrop_var_phi2_trans, sigma2_beta_prior = NULL, alpha_Lambda_prior = NULL, sigma2_A_prior = NULL, alpha_phi1_prior = NULL, beta_phi1_prior = NULL, alpha_phi2_prior = NULL, beta_phi2_prior = NULL, beta_init = NULL, Lambda_init = NULL, delta_init = NULL, w1_init = NULL, w2_init = NULL, A11_init = NULL, A22_init = NULL, A21_init = NULL, phi1_init = NULL, phi2_init = NULL) {
    .Call(`_CWVSmix_CWVSmix`, mcmc_samples, p, q, y, x, z, mh_scale_Lambda, metrop_var_A11_trans, metrop_var_A22_trans, metrop_var_phi1_trans, metrop_var_phi2_trans, sigma2_beta_prior, alpha_Lambda_prior, sigma2_A_prior, alpha_phi1_prior, beta_phi1_prior, alpha_phi2_prior, beta_phi2_prior, beta_init, Lambda_init, delta_init, w1_init, w2_init, A11_init, A22_init, A21_init, phi1_init, phi2_init)
}

Lambda_update <- function(Lambda_old, ind, p, q, x, z, alpha_Lambda, w, gamma, beta, eta_full, metrop_scale_Lambda, acctot_Lambda) {
    .Call(`_CWVSmix_Lambda_update`, Lambda_old, ind, p, q, x, z, alpha_Lambda, w, gamma, beta, eta_full, metrop_scale_Lambda, acctot_Lambda)
}

beta_update <- function(p, q, x, z, sigma2_beta, w, gamma, Lambda_old, eta_full) {
    .Call(`_CWVSmix_beta_update`, p, q, x, z, sigma2_beta, w, gamma, Lambda_old, eta_full)
}

delta_star_update <- function(delta, w1_old, w2_old, A22_old, A21_old) {
    .Call(`_CWVSmix_delta_star_update`, delta, w1_old, w2_old, A22_old, A21_old)
}

delta_update <- function(delta_old, p, q, y, x, z, w, gamma, beta, Lambda, w1_old, w2_old, A11_old, A22_old, A21_old) {
    .Call(`_CWVSmix_delta_update`, delta_old, p, q, y, x, z, w, gamma, beta, Lambda, w1_old, w2_old, A11_old, A22_old, A21_old)
}

neg_two_loglike_update <- function(p, q, y, x, z, beta, Lambda, eta_full) {
    .Call(`_CWVSmix_neg_two_loglike_update`, p, q, y, x, z, beta, Lambda, eta_full)
}

phi_update <- function(phi_old, alpha_phi, beta_phi, w, temporal_corr_info, metrop_var_phi_trans, acctot_phi_trans) {
    .Call(`_CWVSmix_phi_update`, phi_old, alpha_phi, beta_phi, w, temporal_corr_info, metrop_var_phi_trans, acctot_phi_trans)
}

rcpp_pgdraw <- function(b, c) {
    .Call(`_CWVSmix_rcpp_pgdraw`, b, c)
}

rtnorm_gibbs <- function(n, mu, sigma, a, b) {
    .Call(`_CWVSmix_rtnorm_gibbs`, n, mu, sigma, a, b)
}

temporal_corr_fun <- function(p_z, phi) {
    .Call(`_CWVSmix_temporal_corr_fun`, p_z, phi)
}

w1_update <- function(p, q, x, z, w, gamma, beta, Lambda, delta, delta_star, w2_old, A11_old, A22_old, A21_old, temporal_corr_info1) {
    .Call(`_CWVSmix_w1_update`, p, q, x, z, w, gamma, beta, Lambda, delta, delta_star, w2_old, A11_old, A22_old, A21_old, temporal_corr_info1)
}

w2_update <- function(p, z, delta_star, w1, A22_old, A21_old, corr_inv2) {
    .Call(`_CWVSmix_w2_update`, p, z, delta_star, w1, A22_old, A21_old, corr_inv2)
}

w_update <- function(p, q, y, x, z, beta_old, Lambda_old, eta_full) {
    .Call(`_CWVSmix_w_update`, p, q, y, x, z, beta_old, Lambda_old, eta_full)
}

