# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

CWMix <- function(mcmc_samples, p, q, y, x, z, metrop_var_phi_trans, metrop_scale_Lambda, sigma2_beta_prior = NULL, alpha_beta_sigma2_prior = NULL, beta_beta_sigma2_prior = NULL, alpha_beta_phi_prior = NULL, beta_beta_phi_prior = NULL, alpha_Lambda_prior = NULL, beta_init = NULL, eta_init = NULL, sigma2_eta_init = NULL, beta_sigma2_init = NULL, phi_init = NULL, beta_phi_init = NULL, Lambda_init = NULL) {
    .Call(`_CWMix_CWMix`, mcmc_samples, p, q, y, x, z, metrop_var_phi_trans, metrop_scale_Lambda, sigma2_beta_prior, alpha_beta_sigma2_prior, beta_beta_sigma2_prior, alpha_beta_phi_prior, beta_beta_phi_prior, alpha_Lambda_prior, beta_init, eta_init, sigma2_eta_init, beta_sigma2_init, phi_init, beta_phi_init, Lambda_init)
}

Lambda_update <- function(Lambda_old, ind, p, q, x, z, alpha_Lambda, w, gamma, beta, eta, metrop_scale_Lambda, acctot_Lambda) {
    .Call(`_CWMix_Lambda_update`, Lambda_old, ind, p, q, x, z, alpha_Lambda, w, gamma, beta, eta, metrop_scale_Lambda, acctot_Lambda)
}

beta_phi_update <- function(q, phi, alpha_beta_phi, beta_beta_phi) {
    .Call(`_CWMix_beta_phi_update`, q, phi, alpha_beta_phi, beta_beta_phi)
}

beta_sigma2_update <- function(q, sigma2_eta, alpha_beta_sigma2, beta_beta_sigma2) {
    .Call(`_CWMix_beta_sigma2_update`, q, sigma2_eta, alpha_beta_sigma2, beta_beta_sigma2)
}

beta_update <- function(p, q, x, z, sigma2_beta, w, gamma, eta_old, Lambda_old) {
    .Call(`_CWMix_beta_update`, p, q, x, z, sigma2_beta, w, gamma, eta_old, Lambda_old)
}

eta_update <- function(p, q, x, z, w, gamma, beta, sigma2_eta, temporal_corr_info, Lambda_old) {
    .Call(`_CWMix_eta_update`, p, q, x, z, w, gamma, beta, sigma2_eta, temporal_corr_info, Lambda_old)
}

neg_two_loglike_update <- function(p, q, y, x, z, beta, eta, Lambda) {
    .Call(`_CWMix_neg_two_loglike_update`, p, q, y, x, z, beta, eta, Lambda)
}

phi_update <- function(phi_old, eta, sigma2_eta, temporal_corr_info, beta_phi_old, metrop_var_phi_trans, acctot_phi_trans) {
    .Call(`_CWMix_phi_update`, phi_old, eta, sigma2_eta, temporal_corr_info, beta_phi_old, metrop_var_phi_trans, acctot_phi_trans)
}

rcpp_pgdraw <- function(b, c) {
    .Call(`_CWMix_rcpp_pgdraw`, b, c)
}

sigma2_eta_update <- function(p, z, eta, corr_inv, beta_sigma2_old) {
    .Call(`_CWMix_sigma2_eta_update`, p, z, eta, corr_inv, beta_sigma2_old)
}

temporal_corr_fun <- function(p_z, phi) {
    .Call(`_CWMix_temporal_corr_fun`, p_z, phi)
}

w_update <- function(p, q, y, x, z, beta_old, eta_old, Lambda_old) {
    .Call(`_CWMix_w_update`, p, q, y, x, z, beta_old, eta_old, Lambda_old)
}

