# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

A11_update <- function(A11_old, n, p, m, x, z, sigma2_A, w, gamma, beta, delta, w1, risk_sum, metrop_var_A11_trans, acctot_A11_trans) {
    .Call(`_CWVSmix_A11_update`, A11_old, n, p, m, x, z, sigma2_A, w, gamma, beta, delta, w1, risk_sum, metrop_var_A11_trans, acctot_A11_trans)
}

A21_update <- function(sigma2_A, delta_star, w1, w2, A22) {
    .Call(`_CWVSmix_A21_update`, sigma2_A, delta_star, w1, w2, A22)
}

A22_update <- function(A22_old, m, sigma2_A, delta_star, w1, w2, A21_old, metrop_var_A22_trans, acctot_A22_trans) {
    .Call(`_CWVSmix_A22_update`, A22_old, m, sigma2_A, delta_star, w1, w2, A21_old, metrop_var_A22_trans, acctot_A22_trans)
}

CWVSmix <- function(mcmc_samples, p, y, x, z, metrop_var_lambda_trans, metrop_var_rho_trans, metrop_var_A11_trans, metrop_var_A22_trans, metrop_var_phi1_trans, metrop_var_phi2_trans, likelihood_indicator, a_sigma2_epsilon_prior = NULL, b_sigma2_epsilon_prior = NULL, sigma2_beta_prior = NULL, alpha_rho_prior = NULL, beta_rho_prior = NULL, sigma2_A_prior = NULL, alpha_phi1_prior = NULL, beta_phi1_prior = NULL, alpha_phi2_prior = NULL, beta_phi2_prior = NULL, sigma2_epsilon_init = NULL, beta_init = NULL, rho_init = NULL, delta_init = NULL, w1_init = NULL, w2_init = NULL, A11_init = NULL, A22_init = NULL, A21_init = NULL, phi1_init = NULL, phi2_init = NULL) {
    .Call(`_CWVSmix_CWVSmix`, mcmc_samples, p, y, x, z, metrop_var_lambda_trans, metrop_var_rho_trans, metrop_var_A11_trans, metrop_var_A22_trans, metrop_var_phi1_trans, metrop_var_phi2_trans, likelihood_indicator, a_sigma2_epsilon_prior, b_sigma2_epsilon_prior, sigma2_beta_prior, alpha_rho_prior, beta_rho_prior, sigma2_A_prior, alpha_phi1_prior, beta_phi1_prior, alpha_phi2_prior, beta_phi2_prior, sigma2_epsilon_init, beta_init, rho_init, delta_init, w1_init, w2_init, A11_init, A22_init, A21_init, phi1_init, phi2_init)
}

beta_update <- function(n, p, m, p_x, x, z, sigma2_beta, w, gamma, eta_full, risk_sum) {
    .Call(`_CWVSmix_beta_update`, n, p, m, p_x, x, z, sigma2_beta, w, gamma, eta_full, risk_sum)
}

delta_star_update <- function(m, delta, w1_old, w2_old, A22_old, A21_old) {
    .Call(`_CWVSmix_delta_star_update`, m, delta, w1_old, w2_old, A22_old, A21_old)
}

delta_update <- function(delta_old, n, p, m, y, x, z, w, gamma, beta, w1_old, w2_old, A11_old, A22_old, A21_old, eta_full, risk_sum) {
    .Call(`_CWVSmix_delta_update`, delta_old, n, p, m, y, x, z, w, gamma, beta, w1_old, w2_old, A11_old, A22_old, A21_old, eta_full, risk_sum)
}

exp_rs <- function(a, b) {
    .Call(`_CWVSmix_exp_rs`, a, b)
}

half_norm_rs <- function(a, b) {
    .Call(`_CWVSmix_half_norm_rs`, a, b)
}

lambda_update <- function(lambda_star, lambda_old, ind, p, m, x, z, w, gamma, beta, eta_full, risk_sum, temporal_corr_inv_old, metrop_var_lambda_trans, acctot_lambda) {
    .Call(`_CWVSmix_lambda_update`, lambda_star, lambda_old, ind, p, m, x, z, w, gamma, beta, eta_full, risk_sum, temporal_corr_inv_old, metrop_var_lambda_trans, acctot_lambda)
}

neg_two_loglike_update <- function(n, p, m, y, x, z, likelihood_indicator, sigma2_epsilon, beta, eta_full, risk_sum) {
    .Call(`_CWVSmix_neg_two_loglike_update`, n, p, m, y, x, z, likelihood_indicator, sigma2_epsilon, beta, eta_full, risk_sum)
}

norm_rs <- function(a, b) {
    .Call(`_CWVSmix_norm_rs`, a, b)
}

phi_update <- function(phi_old, m, alpha_phi, beta_phi, w, temporal_corr_info, metrop_var_phi_trans, acctot_phi_trans) {
    .Call(`_CWVSmix_phi_update`, phi_old, m, alpha_phi, beta_phi, w, temporal_corr_info, metrop_var_phi_trans, acctot_phi_trans)
}

rcpp_pgdraw <- function(b, c) {
    .Call(`_CWVSmix_rcpp_pgdraw`, b, c)
}

rho_update <- function(rho_old, p, m, alpha_rho, beta_rho, lambda_star, temporal_corr_info, metrop_var_rho_trans, acctot_rho_trans) {
    .Call(`_CWVSmix_rho_update`, rho_old, p, m, alpha_rho, beta_rho, lambda_star, temporal_corr_info, metrop_var_rho_trans, acctot_rho_trans)
}

rnorm_trunc <- function(mu, sigma, lower, upper) {
    .Call(`_CWVSmix_rnorm_trunc`, mu, sigma, lower, upper)
}

sigma2_epsilon_update <- function(n, p, m, y, x, z, likelihood_indicator, a_sigma2_epsilon, b_sigma2_epsilon, beta_old, eta_full, risk_sum) {
    .Call(`_CWVSmix_sigma2_epsilon_update`, n, p, m, y, x, z, likelihood_indicator, a_sigma2_epsilon, b_sigma2_epsilon, beta_old, eta_full, risk_sum)
}

temporal_corr_fun <- function(p_z, phi) {
    .Call(`_CWVSmix_temporal_corr_fun`, p_z, phi)
}

unif_rs <- function(a, b) {
    .Call(`_CWVSmix_unif_rs`, a, b)
}

w1_update <- function(n, p, m, x, z, w, gamma, beta, delta, delta_star, w2_old, A11_old, A22_old, A21_old, risk_sum, corr_inv1) {
    .Call(`_CWVSmix_w1_update`, n, p, m, x, z, w, gamma, beta, delta, delta_star, w2_old, A11_old, A22_old, A21_old, risk_sum, corr_inv1)
}

w2_update <- function(p, m, z, delta_star, w1, A22_old, A21_old, corr_inv2) {
    .Call(`_CWVSmix_w2_update`, p, m, z, delta_star, w1, A22_old, A21_old, corr_inv2)
}

w_update <- function(n, p, m, y, x, z, beta_old, eta_full, risk_sum) {
    .Call(`_CWVSmix_w_update`, n, p, m, y, x, z, beta_old, eta_full, risk_sum)
}

